apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
spec:
  containers:
    - image: curlimages/curl:latest
      name: curl
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do 
            echo "$(date) $(curl -s -o /dev/null -w "HTTP %{http_code}\n" http://nginx-deploy.default.svc.cluster.local)"
            sleep 0.2
          done
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
