apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - image: nginx:1.27.0
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: 256Mi
            requests:
              cpu: "200m"
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 25
            periodSeconds: 30

          volumeMounts:
            - name: ebs-volume
              mountPath: /usr/share/nginx/html/data

      volumes:
        - name: ebs-volume
          persistentVolumeClaim:
            claimName: block-pvc
