apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-update-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-update
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: mikey
